name: ModsDownload
on:
  workflow_dispatch:
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Modpack Downloader CLI
        run: |
          mkdir ${GITHUB_WORKSPACE}/downloader
          wget https://github.com/Nincraft/ModPackDownloader/releases/download/0.6.1/ModpackDownloader-cli-0.6.1.jar -O ${GITHUB_WORKSPACE}/downloader/ModpackDownloader-cli-0.6.1.jar
      - name: Download Mods
        run: sudo ${JAVA_HOME_11_X64}/bin/java -jar ${GITHUB_WORKSPACE}/downloader/ModpackDownloader-cli-0.6.1.jar -manifest ${GITHUB_WORKSPACE}/manifest.json -folder ${GITHUB_WORKSPACE}/mods

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Mods
          path: mods
          retention-days: 5
